-- Draft migration — review and adjust table/schema names before running.
-- Backs the refresh-token rotation flow in Flagship.Application.Services.RefreshTokenService.
-- Tokens themselves are opaque random values generated by the app; only their
-- SHA-256 hash is ever stored here, so a database read alone can't be replayed.

CREATE TABLE dbo.RefreshTokens (
    refresh_token_id       BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    user_id                BIGINT NOT NULL,
    token_hash             NVARCHAR(64) NOT NULL,
    created_at_utc         DATETIME2 NOT NULL,
    expires_at_utc         DATETIME2 NOT NULL,
    revoked_at_utc         DATETIME2 NULL,
    replaced_by_token_hash NVARCHAR(64) NULL,
    CONSTRAINT FK_RefreshTokens_Users FOREIGN KEY (user_id) REFERENCES dbo.Users (user_id)
);
GO

CREATE UNIQUE INDEX UX_RefreshTokens_TokenHash ON dbo.RefreshTokens (token_hash);
GO

CREATE INDEX IX_RefreshTokens_UserId ON dbo.RefreshTokens (user_id) INCLUDE (revoked_at_utc);
GO
